fleetimpact/fleetimpact/urls.py
from django.conf.urls import patterns, include, url
from fleetimpact.views import homepage, dashboard, thanks, signin, test_maps, test_maps2, test_maps3, test_maps4, homepage2
from django.conf import settings
from django.views.generic import TemplateView

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    url(r'^$', homepage),
    url(r'^bienvenu$',homepage),
    url(r'^acceuil$', dashboard),
    url(r'^(w{1,20})\.\acceuil$',dashboard),
    url(r'^thanks$', thanks),
    url(r'^signin$', signin),
    url(r'^maps$', test_maps),
    url(r'^maps2$', test_maps2),
    url(r'^maps3$', test_maps3),
    url(r'^maps4$', test_maps4),
    url(r'^acceuil2$', homepage2),
    # url(r'^$', 'fleetimpact.views.home', name='home'),
    # url(r'^fleetimpact/', include('fleetimpact.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    url(r'^signin/', include('signin.urls', namespace="signin")),
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^todo/', include('todo.urls', namespace="todo")),
    url(r'^forum/', include('forum.urls', namespace="forum")),
    url(r'^ecotaxe/', include('ecotaxe.urls', namespace="ecotaxe")),
    url(r'^accounts/', include('registration.backends.default.urls', namespace="accounts")),
    url(r'^$', TemplateView.as_view(template_name = 'index.html'), name='index'),
)

fleetimpact/forum/urls.py
from django.conf.urls import patterns, url
from forum import views

urlpatterns = patterns('',
    url(r'^$',views.main, name="main"),
    url(r'^forum/(\d+)/$', views.forum, name="forum"),
    url(r'^thread/(\d+)/$', 'thread'),
)

fleetimpact/todo/urls.py
from django.conf.urls import patterns, url

from todo import views

urlpatterns = patterns('',
    url(r'^mark_done/(\d*)/$', "views.mark_done"),
   
)

fleetimpact/forum/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib import admin
from string import join
from fleetimpact.settings import MEDIA_ROOT

class Forum(models.Model):
    title = models.CharField(max_length=60)
    def __unicode__(self):
        return self.title

    def num_posts(self):
        return sum([t.num_posts() for t in self.thread_set.all()])

    def last_post(self):
        if self.thread_set.count():
            last = None
            for t in self.thread_set.all():
                l = t.last_post()
                if l:
                    if not last: last = l 
                elif l.created > last.created: last = l
            return last

class Thread(models.Model):
    title = models.CharField(max_length=60)
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, blank=True, null=True)
    forum = models.ForeignKey(Forum)

    def __unicode__(self):
        return unicode(self.creator) + " - " + self.title

    def num_posts(self):
        return self.post_set.count()

    def num_replies(self):
        return self.post_set.count()-1
    
    def last_post(self):
        if self.post_set.count():
            return self.post_set.order_by("created")[0]

class Post(models.Model):
    title = models.CharField(max_length=60)
    created = models.DateTimeField(auto_now_add=True)
    creator = models.ForeignKey(User, blank=True, null=True)
    thread = models.ForeignKey(Thread)
    body = models.TextField(max_length=10000)

    def __unicode__(self):
        return u"%s - %s - %s" % (self.creator, self.thread, self.title)

    def short(self):
        return u"%s - %s\n%s" % (self.creator, self.title, self.created.strftime("%b %d, %I:%M %p"))
    short.allow_tags = True

### Admin

class ForumAdmin(admin.ModelAdmin):
    pass

class ThreadAdmin(admin.ModelAdmin):
    list_display = ["title", "forum", "creator", "created"]
    list_filter = ["forum", "creator"]

class PostAdmin(admin.ModelAdmin):
    search_fields = ["title", "creator"]
    list_display = ["title", "thread", "creator", "created"]

admin.site.register(Forum, ForumAdmin)
admin.site.register(Thread, ThreadAdmin)
admin.site.register(Post, PostAdmin)

fleetimpact/forum/views.py
from django.core.urlresolvers import reverse
from fleetimpact.settings import MEDIA_ROOT, MEDIA_URL
from forum.models import Forum, Thread, Post
from django.shortcuts import render_to_response
from django.core.paginator import Paginator
from django.core.context_processors import csrf


def main(request):
    """Main listing."""
    forums = Forum.objects.all()
    return render_to_response("forum/list.html", dict(forums=forums, user=request.user))


def add_csrf(request, ** kwargs):
    d = dict(user=request.user, ** kwargs)
    d.update(csrf(request))
    return d

def mk_paginator(request, items, num_items):
    """Create and return a paginator."""
    paginator = Paginator(items, num_items)
    try: page = int(request.GET.get("page", '1'))
    except ValueError: page = 1

    try:
        items = paginator.page(page)
    except (InvalidPage, EmptyPage):
        items = paginator.page(paginator.num_pages)
    return items


def forum(request, pk):
    """Listing of threads in a forum."""
    threads = Thread.objects.filter(forum=pk).order_by("-created")
    threads = mk_paginator(request, threads, 20)
    return render_to_response("forum/forum.html", add_csrf(request, threads=threads, pk=pk))


def thread(request, pk):
    """Listing of posts in a thread."""
    posts = Post.objects.filter(thread=pk).order_by("created")
    posts = mk_paginator(request, posts, 15)
    title = Thread.objects.get(pk=pk).title
    return render_to_response("forum/threads.html", add_csrf(request, posts=posts, pk=pk, title=title, media_url=MEDIA_URL))


def post(request, ptype, pk):
    """Display a post form."""
    action = reverse('fleetimpact.forum.views.%s' % ptype, args=[pk])
    if ptype == "new_thread":
        title = "Start New Topic"
        subject = ''
    elif ptype == "reply":
        title = "Reply"
        subject = "Re: " + Thread.objects.get(pk=pk).title

    return render_to_response("forum/post.html", add_csrf(request, subject=subject,
        action=action, title=title))


def new_thread(request, pk):
    """Start a new thread."""
    p = request.POST
    if p["subject"] and p["body"]:
        forum = Forum.objects.get(pk=pk)
        thread = Thread.objects.create(forum=forum, title=p["subject"], creator=request.user)
        Post.objects.create(thread=thread, title=p["subject"], body=p["body"], creator=request.user)
    return HttpResponseRedirect(reverse("fleetimpact.forum.views.forum", args=[pk]))


def reply(request, pk):
    """Reply to a thread."""
    p = request.POST
    if p["body"]:
        thread = Thread.objects.get(pk=pk)
        post = Post.objects.create(thread=thread, title=p["subject"], body=p["body"],
            creator=request.user)
    return HttpResponseRedirect(reverse("fleetimpact.forum.views.thread", args=[pk]) + "?page=last")

fleetimpact/forum/templates/forum/fbase.html
{% if not user.is_authenticated %}<a href="/accounts/login/?next=/forum/">Login</a> | <a> href="/accounts/register/">Register></a>{% endif %}

{% if user.is_authenticated %}<a href="/accounts/logout/?next=/forum/">Logout<a> {% endif %}

fleetimpact/forum/templates/forum/forum.html
<!-- Threads  -->
<a id="new_topic" class="buttont" href= "{% url 'forum:post' "new_thread" pk %}">Start New Topic</a>
<br />
<br />

<div id="list">
<table border="0" cellpadding="4" width="100%">
    <tr>
        <td>Topics</td>
        <td>Replies</td>
        <td>Last post</td>
        <td></td>
    </tr>

    {% for thread in threads.object_list %}
    <tr>
        <td {% if forloop.last %}class="last"{% endif %}>
        <div class="title"> <a href="{% url "forum.views.thread" thread.pk %}">{{ thread.title }}</a>
            </div></td>
        <td {% if forloop.last %}class="last"{% endif %}>{{ thread.num_replies }}</td>
        <td {% if forloop.last %}class="last"{% endif %}>
            {{ thread.last_post.short|linebreaksbr }}</td>
        <td {% if forloop.last %}class="last"{% endif %}>
            <a class="button" href="{% url "forum.views.thread" thread.pk %}">VIEW</a>
        </td>
    </tr>

    {% endfor %}
</table>
</div>

<!-- Next/Prev page links  -->
{% if threads.object_list and threads.paginator.num_pages > 1 %}
<div class="pagination">
    <span class="step-links">
        {% if threads.has_previous %}
            <a href= "?page={{ threads.previous_page_number }}">previous &lt;&lt; </a>
        {% endif %}

        <span class="current">
            &nbsp;Page {{ threads.number }} of {{ threads.paginator.num_pages }}
        </span>

        {% if threads.has_next %}
            <a href="?page={{ threads.next_page_number }}"> &gt;&gt; next</a>
        {% endif %}
    </span>
</div>
{% endif %}

fleetimpact/forum/templates/forum/list.html
<!-- Forums -->
<div id="list">
<table border="0" cellpading="4" width="100%">
  <tr>
    <td></td>
    <td>Posts</td>
    <td>Last Post</td>
    <td></td>
  </tr>

  {% for forum in forums %}
  <tr>
    <td {% if forloop.last %} class="last" {% endif %}>
    <div class = "title"> <a href="{% url 'forum:forum' forum.pk %}"> {{forum.title }}</a>
    </div></td>
    <td> {% if forloop.last %} class= "last" {% endif %}> {{ forum.num_posts }} </td>
    <td> {% if forloop.last %} class= "last" {% endif %}>
         {{ forum.last_post.short | linebreaksbr }}</td>
    <td {% if forloop.last %}class= "last" {% endif %}>
      <a class="button" href=" {% url 'forum:forum' forum.pk %}">VIEW</a>
    </td>
  </tr>

  {% endfor %}
</div>
	

fleetimpact/forum/templates/forum/thread.html
<!-- Posts -->
<div class="title"> {{title }}</div>
<div id="list">

  {% for post in posts.object_list %}
     <div class="post">
       <span class="title">{{ post.title }}</span><br />
       by {{ post.creator }} | <span class="date">{{ post.created }}</span> <br /><br /> {{ post.body }}<br />
     </div>
  {% endfor %}

</div>

<a class="button" href="{% url "forum.views.post" 'reply' pk %}">Reply</a>